name: Build Custom Frida Gadget

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Frida Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive 

      - name: Install Build Dependencies
        run: |
          brew update
          brew install node npm ninja meson pkg-config vala
          npm install -g frida-compile
          python3 -m pip install setuptools --break-system-packages

      - name: Inject Custom Anti-Cheat Kills
        run: |
          cp bs-custom-files/gadget-darwin.m subprojects/frida-core/lib/gadget/gadget-darwin.m

      - name: Build iOS Gadget
        run: |
          export FRIDA_PYTHON=disabled
          export FRIDA_NODE=disabled
          export FRIDA_SWIFT=disabled
          export FRIDA_TOOLS=disabled
          make core-ios

      - name: Package gadget.framework
        run: |
          mkdir -p gadget.framework/ss
          cp build/frida-ios-arm64/lib/frida/64/frida-gadget.dylib gadget.framework/gadget
          cp bs-custom-files/load.lebronjs gadget.framework/ss/load.lebronjs

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gadget-framework
          path: gadget.framework
